<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Training_Platform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="E:\Data_My Courses\.Netcourse\Data\Lec_24\reops-template\falcon-v3.14.0\public\assets\img\icons\spot-illustrations\falcon.png" Link="wwwroot\images\admin_layout\falcon.png" />
    <Content Include="E:\Data_My Courses\.Netcourse\Data\Lec_24\reops-template\falcon-v3.14.0\public\vendors\simplebar\simplebar.min.css" Link="wwwroot\css\admin\simplebar.min.css" />
  </ItemGroup>


  

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>


  

  <ItemGroup>
    <Folder Include="Areas\Trainee\Controllers\" />
    <Folder Include="Areas\Trainer\Controllers\" />
    <Folder Include="wwwroot\assets\trainee\" />
    <Folder Include="wwwroot\assets\trainer\" />
    <Folder Include="wwwroot\css\trainer\" />
    <Folder Include="wwwroot\css\trainee\" />
    <Folder Include="wwwroot\images\admin_layout\" />
    <Folder Include="wwwroot\images\trainer_layout\" />
    <Folder Include="wwwroot\images\trainee_layout\" />
    <Folder Include="wwwroot\js\trainee\" />
    <Folder Include="wwwroot\js\trainer\" />
  </ItemGroup>


  

  <ItemGroup>
    <None Include="E:\Data_My Courses\.Netcourse\Data\Lec_24\reops-template\falcon-v3.14.0\public\vendors\simplebar\simplebar.min.js" Link="wwwroot\js\admin\simplebar.min.js" />
  </ItemGroup>

</Project>
